spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME} 
    username: ${DATABASE_USERNAME} 
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

api:
  secret: ${API_SECRET}

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}
  public-url: ${MINIO_PUBLIC_URL:http://localhost:9000}